@mkdir build >nul
pushd build
@mkdir Win-X64-msvc-release >nul
pushd Win-X64-msvc-release

cmake ../../ -A X64 -DLIEF_PYTHON_API=OFF -DLIEF_ELF=OFF -DLIEF_MACHO=OFF -DLIEF_OAT=OFF -DLIEF_MACHO=OFF -DLIEF_OAT=OFF -DLIEF_DEX=OFF -DLIEF_VDEX=OFF -DLIEF_ART=OFF -DLIEF_EXAMPLES=OFF -DLIEF_C_API=OFF -DLIEF_USE_CCACHE=OFF -DLIEF_LOGGING=OFF -DLIEF_ENABLE_JSON=OFF -DBUILD_SHARE_LIBS=OFF -DCMAKE_BUILD_TYPE=Release

popd
popd